apiVersion: v1
kind: Secret
metadata:
  name: alarik-credentials
type: Opaque
stringData:
  ADMIN_USERNAME: alarik
  ADMIN_PASSWORD: alarik
---
apiVersion: v1
kind: Secret
metadata:
  name: alarik-access-keys
type: Opaque
stringData:
  DEFAULT_ACCESS_KEY: wrt-key
  DEFAULT_SECRET_KEY: wrt-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarik
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alarik
  template:
    metadata:
      labels:
        app: alarik
    spec:
      containers:
      - name: alarik
        image: ghcr.io/achtungsoftware/alarik:latest
        envFrom:
          - secretRef:
              name: alarik-credentials
          - secretRef:
              name: alarik-access-keys
        env:
        - name: API_BASE_URL
          value: http://localhost:30090
        - name: CONSOLE_BASE_URL
          value: http://localhost:30100
        - name: JWT
          value: "alarik-jwt"
        - name: ALLOW_ACCOUNT_CREATION
          value: "false"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: data
            mountPath: /app/Storage
        resources:
          # adjust asap to your set-up
          requests:
            memory: "512M"
            cpu: "100m"
          limits:
            memory: "768M"
            cpu: "250m"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarik-console
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alarik-console
  template:
    metadata:
      labels:
        app: alarik-console
    spec:
      initContainers:
      - name: create-bucket
        image: curlimages/curl:8.17.0
        command: [ "sh", "-c" ]
        args:
          - |
            until curl -X 'GET' http://alarik-service:8080/api/v1/health -s --head --fail; \
            do echo 'Waiting for Alarik backend'; sleep 5; done; \
            curl -X 'POST' http://alarik-service:8080/api/v1/buckets -s \
            -H 'Content-Type: application/json' \
            -H 'X-Access-Key: wrt-key' \
            -H 'X-Secret-Key: wrt-secret' \
            -d '{"name":"wrt", "versioningEnabled":true}'
      containers:
      - name: alarik-console
        image: ghcr.io/achtungsoftware/alarik-console:latest
        env:
        - name: NUXT_PUBLIC_API_BASE_URL
          value: http://localhost:30090
        - name: NUXT_PUBLIC_CONSOLE_BASE_URL
          value: http://localhost:30100
        - name: NUXT_PUBLIC_ALLOW_ACCOUNT_CREATION
          value: "false"
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: data
            mountPath: /app/Storage
        resources:
          # adjust asap to your set-up
          requests:
            memory: "512M"
            cpu: "100m"
          limits:
            memory: "768M"
            cpu: "250m"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alarik-service
spec:
  type: NodePort
  selector:
    app: alarik
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: alarik-console-service
spec:
  type: NodePort
  selector:
    app: alarik-console
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100