apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-job-manager-config
data:
  local.config.yml: |
    server:
      bind:
        host: 0.0.0.0
        port: 80
      url: http://localhost:30080/pygeoapi/
      mimetype: application/json; charset=UTF-8
      encoding: utf-8
      gzip: false
      languages:
        - en-US
      cors: true
      pretty_print: true
      limits:
        default_items: 50
        max_items: 1000
        max_distance_x: 25
        max_distance_y: 25
        max_distance_units: m
        on_exceed: throttle
      map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
      manager:
        name: pygeoapi_k8s_manager.KubernetesManager
        logging:
          botocore: INFO
          kubernetes: INFO
          pygeoapi.l10n: ERROR
        # enable k8s finalizer controller
        finalizer_controller: true
      admin: false # enable admin api
    logging:
      level: DEBUG
      logfile: /dev/stdout
      logformat: '[%(asctime)s | %(name)s::%(module)s.py:%(lineno)d | %(process)d] %(levelname)s - %(message)s'
    metadata:
      identification:
        title:
          en: pygeoapi default instance
          fr: instance par défaut de pygeoapi
        description:
          en: pygeoapi provides an API to geospatial data
          fr: pygeoapi fournit une API aux données géospatiales
        keywords:
          en:
            - geospatial
            - data
            - api
          fr:
            - géospatiale
            - données
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
      license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
      provider:
        name: Organization Name
        url: https://pygeoapi.io
      contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact
    resources:
      hello-world-k8s:
        type: process
        processor:
          name: pygeoapi_k8s_manager.process.HelloWorldK8sProcessor
      hello-world-k8s-sleep:
        type: process
        processor:
          name: pygeoapi_k8s_manager.process.HelloWorldK8sProcessor
          command:
            - date
            - echo start and now sleeping 10s
            - sleep 10
      hello-world-k8s-sleep-failing:
        type: process
        processor:
          name: pygeoapi_k8s_manager.process.HelloWorldK8sProcessor
          command:
            - date
            - echo start and now sleeping 10s
            - sleep 10
            - echo oh no, we are failing
            - exit 1
      weather-routing-tool:
        type: process
        processor:
          name: pygeoapi_k8s_manager.process.GenericImageProcessor
          check_auth: False
          metadata:
            version: 0.1
            id: weather-routing-tool
            title:
              en: "Weather Routing Tool"
            description:
              en: "Weather Routing Tool"
            keywords:
              - weather routing tool
              - generic image processor
              - k8s
              - k8s manager
              - KubernetesManager
            links:
              - type: text/html
                rel: about
                title: Processor Code Repository
                href: https://github.com/52North/pygeoapi_k8s-manager/blob/main/src/pygeoapi_k8s_manager/process/generic_image.py
                hreflang: en-UK
              - type: text/html
                rel: about
                title: WeatherRoutingTool API Code Repository
                href: https://github.com/52North/WRT-API
                hreflang: en-UK
              - type: text/html
                rel: about
                title: WeatherRoutingTool Code Repository
                href: https://github.com/52North/WeatherRoutingTool
                hreflang: en-UK
            inputs:
              wrt_*:
                title: Weather Routing Tool config parameter
                description: Input parameters with the prefix "wrt_" are mapped to the corresponding config parameter (https://52north.github.io/WeatherRoutingTool/source/configuration.html). Use all lowercase characters for the process inputs.
                schema:
                  type: string
              wrt_departure_time:
                title: Departure time
                description: Departure time in the format 'yyyy-mm-ddThh:mmZ'. Maps to the config parameter DEPARTURE_TIME.
                schema:
                  type: string
              wrt_default_route:
                title: Default route
                description: Source and destination in the format '(lat_start, lon_start, lat_end, lon_end)'. Maps to the config parameter DEFAULT_ROUTE.
                schema:
                  type: string
              wrt_default_map:
                title: Default map
                description: Map/bbox in the format '(lat_min, lon_min, lat_max, lon_max)'. Maps to the config parameter DEFAULT_MAP.
                schema:
                  type: string
            outputs:
              logs:
                title: logs
                description: The logs of the job
                schema:
                  type: string
                  contentMediaType: application/json
            example:
              inputs:
                wrt_departure_time: 2026-03-06T12:00Z
                wrt_default_route: [53.55, 0.16, 52.0, 4.0]
                wrt_default_map: [51.9, 0.0, 53.7, 4.3]
                wrt_boat_speed: 6
                wrt_algorithm_type: gcr_slider
                wrt_contraints_list: ["land_crossing_global_land_mask", "on_map"]
          default_image: 52north/weather-routing-api:local
          # OPTIONAL
          # image_pull_secrets: default-secret
          env:
          - name: PROCESS_OUTPUTS_BUCKET_ENDPOINT
            value: http://alarik-service:8080
          - name: PROCESS_OUTPUTS_PUBLIC_BUCKET_ENDPOINT
            value: http://localhost:30100
          - name: PROCESS_OUTPUTS_BUCKET_KEY
            value: wrt-key
          - name: PROCESS_OUTPUTS_BUCKET_SECRET
            value: wrt-secret
          - name: PROCESS_OUTPUTS_BUCKET_NAME
            value: wrt
          - name: PROCESS_OUTPUTS_BUCKET_PATH_PREFIX
            # adds <process-id>/outputs/<job-id> from env variables during runtime
            value: k8s-job-manager/processes/
          - name: PROCESS_OUTPUTS_LOCAL_PATH_PREFIX
            value: /app/workdir/
          - name: WRT_FIGURE_PATH
            value: /app/workdir/figures/
          #- name: CMEMS_USERNAME
          #  secret_name: cmems-credentials
          #  secret_key: user
          #- name: CMEMS_PASSWORD
          #  secret_name: cmems-credentials
          #  secret_key: password
          # resources might need to be adjusted
          resources:
            requests:
              memory: 3G
              cpu: 500m
            limits:
              memory: 10G
              cpu: 2000m
          tolerations:
          - key: "toleration-key"
            value: "toleration-value"
            operator: "Equal"
            effect: "NoSchedule"
